title: Noras awesome Documentation
email: marco.reisert@uniklinik-freiburg.de
description:  This will appear in your document head meta (for Google search results) and in your feed.xml site description. 
remote_theme: pages-themes/dinky@v0.2.0
